/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/4G1xK7WAnLZN-vua/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#ece9f2']} />
      <group {...props} dispose={null}>
        <mesh
          name="Dodecahedron"
          geometry={nodes.Dodecahedron.geometry}
          material={materials.Holo}
          castShadow
          receiveShadow
          position={[-146.95, 186.06, 12.49]}
          rotation={[0.02, -0.02, 0]}
          scale={1}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Holo Material']}
          castShadow
          receiveShadow
          position={[144.07, 109.08, 117.38]}
          rotation={[0.02, -0.02, -0.01]}
          scale={1}
        />
        <mesh
          name="Pyramid"
          geometry={nodes.Pyramid.geometry}
          material={materials['Holo Material']}
          castShadow
          receiveShadow
          position={[-198.91, -85.46, 86.91]}
          rotation={[0.02, -0.02, 0]}
          scale={1}
        />
        <mesh
          name="Helix"
          geometry={nodes.Helix.geometry}
          material={materials['Holo Material']}
          castShadow
          receiveShadow
          position={[182.48, -75.29, 65.48]}
        />
        <group name="Group 2" position={[-10, 27, 239]} rotation={[-0.06, 0, 0]} scale={4.37}>
          <mesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={nodes.EyeLeft.material}
            castShadow
            receiveShadow
            position={[0.7, -379.5, -60]}
            scale={4.33}
          />
          <mesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={nodes.Wolf3D_Hair.material}
            castShadow
            receiveShadow
            position={[0.7, -379.5, -60]}
            scale={4.33}
          />
          <mesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={nodes.EyeRight.material}
            castShadow
            receiveShadow
            position={[0.7, -379.5, -60]}
            scale={4.33}
          />
          <mesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={nodes.Wolf3D_Head.material}
            castShadow
            position={[0.7, -379.5, -60]}
            scale={4.33}
          />
          <mesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={nodes.Wolf3D_Teeth.material}
            castShadow
            receiveShadow
            position={[0.7, -379.5, -60]}
            scale={4.33}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[-265.83, 311.12, 165.16]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.9}
          far={100000}
          near={-1000}
          position={[-0, 103.79, 1239.28]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
